version: '2'
run:
  timeout: 5m
linters:
  default: standard
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - govet
    - gosec
  exclusions:
    generated: lax
    rules:
      - linters: [gosec]
        text: 'G104'
