name: Qodana Static Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Qodana scan
        uses: JetBrains/qodana-action@b588768b6e7e6da579e518bc584f79de0d243692
        with:
          pr-mode: true
          post-pr-comment: true
          use-annotations: true
          upload-result: true
          artifact-name: qodana-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1824243340 }}
          QODANA_ENDPOINT: https://qodana.cloud
